:numbered:

== Executive Summary

Artifactory gives a DevOps team the tools to manage the flow of artifacts from each Devs workstation to the organization’s production environment. Integrating with CI/CD, Artifactory provides an end-to-end, automated solution for storing and tracing artifacts from development to production.

Artifactory can provide security and access control at several levels. From restricting complete repositories down to restricting a single binary.

In combination with {OCP} Artifactory provides a scalable solution, as the use of components in software development continues to grow developers face new challenges. Artifactory provices as a single access point organizing all source and binary resources removing much of the overhead connected to the complexity of developing with open source libraries and other 3rd party components.

Integrating Artifactory with {OCP} build tools, such as Build Pipelines and {s2i} builds provides great flexibility to developers and fine grain control to operators.

// vim: set syntax=asciidoc:
