== Prerequisites

This {RefImpl} requires a few things to be set up properly.

=== {ocp}

All commands, playbooks and configurations require {OCP} or above. Please provide a correctly deployed environment. Please direct special attention to DNS setup.


To set up such an environment, leverage <<ocp-on-vmware>> to deploy to an on premise VMware infrastructure or <<ocp-on-aws>> to deploy to the Amazon public cloud.

=== local client tools

In order to run the Ansible playbooks you need locally installed {ocp} command line tools, git and ansible.

.required local software
[options="header"]
[frame="topbot",grid="none"]
|====
|Software | RPM | Repository
| git | git-1.8.3.1-6.el7_2.1.x86_64 | rhel-7-server-rpms
| ansible | ansible-2.2.0.0-1.el7.noarch | rhel-7-server-ose-3.4-rpms
| oc command | atomic-openshift-clients-3.4.1.5-1.git.0.690b5d4.el7.x86_64 | rhel-7-server-ose-3.4-rpms
|====

WARNING: Due to a bug existing at the time of writing this {RefImpl} it is required to use ansible 2.2.0.0, not 2.2.1.0!

=== An OpenShift project

Please create a project to deploy Artifactory. The user must have all the permissions to create an OpenShift configuration item within this project. The user/project must have access to a certain number of PersistenVolumes:

.required PersistentVolumes
[options="header"]
[frame="topbot",grid="none"]
|====
| PersistentVolume | min. size | used for | used by
| vol0001 | 1Gi | artifactory-backup-artifactory-0 | Artifactory pod
| vol0002 | 1Gi | artifactory-data-artifactory-0 | Artifactory pod
| vol0003 | 1Gi | artifactory-logs-artifactory-0 | Artifactory pod
| vol0004 | 1Gi | artifactory-var-artifactory-0 | Artifactory pod
| vol0005 | 1Gi | artifactory-postgresql | PostgreSQL
|====

Throughout the course of this {RefImpl} we use the project `artifactory-test`.

=== Clone this {RefImpl}

To use the Ansible playbooks and {ocp} configurations provided by this {RefImpl} you need to clone https://github.com/goern/artifactory-on-openshift to your local workstation.
